# 1강. Numpy의 연산

In [2]:
import numpy as np

arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3,)

In [9]:
arr_2d.shape

(3, 3)

## Numpy로 연산하기

### Vector와 Scalar 사이의 연산
- 벡터의 각 원소에 대해서 연산을 진행
$$x = \begin{pmatrix}
1 \\ 
2 \\
3
\end{pmatrix}, c = 5$$

In [12]:
x = np.array([1, 2, 3])
c = 5

print('더하기 : {}'.format(x + c))
print('빼기 : {}'.format(x - c))
print('곱하기 : {}'.format(x * c))
print('나누기 : {}'.format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행
$$y = \begin{pmatrix}
1 \\ 
3 \\
5
\end{pmatrix}, z = \begin{pmatrix}
2 \\ 
9 \\
20
\end{pmatrix}$$

In [13]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print('더하기 : {}'.format(y + z))
print('빼기 : {}'.format(y - z))
print('곱하기 : {}'.format(y * z))
print('나누기 : {}'.format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array의 Indexing
- Python의 List와 유사하나, $[a][b]$가 아닌 $[a, b]$
$$w = \begin{pmatrix}
1 & 2 & 3 & 4 \\ 
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{pmatrix}$$

In [14]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(w[0, 0])
print(w[2, 3])

1
12


### Array의 Slicing
- Array에서 특정 범위의 원하는 원소를 가져오는 경우.
    - 마찬가지로, Python의 List와 유사하게 진행

In [5]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 2, 3 -> 행: 인덱스 0~1 -> [0: 2]
# 6, 7 -> 열: 인덱스 1~2 -> [1: 3]

print(w[0:2, 1:3])
print(w[:, 2:])

[[2 3]
 [6 7]]
[[ 3  4]
 [ 7  8]
 [11 12]]


### Array의 Broadcasting
- Numpy가 연산을 진행하는 특수한 방법
    - 기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능. 하지만 만약 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능하되고, 이를 **Broadcasting**이라 함.
    1. $M \times N, M \times 1$
    2. $M \times N, 1 \times N$
    3. $M \times 1, 1 \times N$

####  1. $M \times N, M \times 1$

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])
x = x[:, None] # x를 전치
print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


#### 2. $M \times N, 1 \times N$

In [21]:
y = np.array([0, 1, -1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


#### 3. $M \times 1, 1 \times N$

In [23]:
t = np.array([1, 2, 3])
t = t[:, None] # transpose

u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]
