# 1강. 선형시스템(Linear System)

## 이론

- **선형시스템**
> Ax = b, 연립일차방정식의 대수적 표현
    - ***가우스 소거법***: 선형시스템을 푸는 방법
    - ***LU 분해***: 가우스 소거법 과정을 행렬로 표현

> **선형대수(Linear Algebra)**의 목표는 어떤 연립일차방정식 문제를 정형적인 방법으로 표현하고 해결하는 방법을 배우는 것.
 - 예를 들면, 변수가 매우 많은 연립일차방정식을 해결하는 방법
     - 이를 행렬을 사용하여 해결. ***Ax= b***의 형태.

- N개의 Linear Equation + M개의 Unknowns(Variables) = N x M Linear System

- 선형시스템을 Ax=b의 형채로 표현하는 방법
    1. 선형시스템의 Unknowns(미지수)를 모아 Column vector(열벡터) ***x***로 표현.
    2. 선형시스템의 Linear Equation(선형방정식)에 대해 다음을 수행.
        - Coefficients(계수)를 모아 ***A***의 row vector(행벡터)로 표현
        - Constant(상수)를 모아 ***b***에 표현.

### 정리: Linear System의 대수적 표현

- m x n 선형시스템의 Ax= b 표현을 정리하면 다음과 같다.
    - 식은 행이고, 행은 식이다.
    - m은 Linear Equation의 개수
    - n은 Unknown의 개수
    - A는 m x n행렬
    - x는 n-벡터
    - b는 m-벡터

## 실습

In [4]:
import numpy as np

In [6]:
# 행렬 코딩
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [7]:
# 벡터 코딩
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


In [8]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [9]:
# 역행렬을 이용한 선형시스템 Ax=b의 해 구하기
# x = np.matmul(A_inv, b)
x = A_inv @ b

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [10]:
# 결과 검증
# bb = np.matmul(A, x)
bb = A @ x

print(bb)
print(np.shape(bb))

if np.linalg.norm(b - bb) < 1e-3:
    print('OK!')
else:
    print('Something wrong...')

[4. 1. 2.]
(3,)
OK!


In [11]:
print(np.linalg.norm(b - bb))

1.88411095042053e-15
